runtime: java
env: flex
# entrypoint: java -Xmx128m -jar info.jar
service: info
runtime_config:
    operating_system: "ubuntu22"
    runtime_version: "17"
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 1
env_variables:
  POSTGRESQL_USERNAME: "postgres"
  POSTGRESQL_PASSWORD: "password"