version: "3"
services:
  api_register:
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      - POSTGRES_USERNAME=root
      - POSTGRES_PASSWORD=password
    ports:
      - "80:8080"
    extra_hosts:
      - "staging.ric-robotics.xyz:127.0.0.1"
    volumes:
      - "./secrets/credentials.json:/usr/local/credentials.json"
    restart: unless-stopped
