server:
  port: ${PORT}
spring:
  cloud:
    gcp:
      project-id: shaped-splicer-397009
      credentials:
        encoded-key: ${GCP_CREDENTIALS_JSON}
      sql:
        enabled: false
      bucket:
        id: idc-system-resources
        dirName: participants
  sql:
    init:
      platform: postgres
  datasource:
    url: jdbc:postgresql://10.21.176.3:5432/ric-database
    username: ${POSTGRESQL_USERNAME}
    password: ${POSTGRESQL_PASSWORD}
    driverClassName: org.postgresql.Driver
    hikari:
      minimum-idle: 5
  jpa:
    hibernate:
      ddl-auto: update
  secured: true

keycloak:
  auth-server-url: https://keycloak.ric-robotics.xyz
  principal-attribute: info-collection-system
  realm: ricsg
  resource: ricsg
  public-client: true
  use-resource-role-mappings: false
  bearer-only: true
  cors: true