server:
  port: 8082
spring:
  cloud:
    gcp:
      credentials:
        location: classpath:prod-sql-credential.json
      project-id: apt-terrain-401911
      sql:
        database-name: ric-database
        instance-connection-name: apt-terrain-401911:asia-southeast1:prd-ric-database
      bucket:
        credential: classpath:dev-bucket-credential.json
        id: idc-system-resources-prd
        dirName: participants
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  datasource:
    username: prd-ric-app-user
    password: password
    hikari:
      minimum-idle: 5
  jpa:
    hibernate:
      ddl-auto: update
  secured: true

keycloak:
  auth-server-url: https://keycloak.ric-robotics.xyz
  principal-attribute: idc-system
  realm: ricsg
  resource: ricsg
  public-client: true
  use-resource-role-mappings: false
  bearer-only: true
  cors: true
  enabled: true