server:
  port: 8082
spring:
  cloud:
    gcp:
      sql:
        database-name: ric-database
        instance-connection-name: shaped-splicer-397009:asia-southeast1:prd-ric-database
      credentials:
        location: classpath:prod-sql-credential.json
      project-id: shaped-splicer-397009
      bucket:
        credential: classpath:dev-bucket-credential.json
        id: idc-system-resources
        dirName: participants
  datasource:
    username: prd-ric-app-user
    password: password
    hikari:
      minimum-idle: 5
  jpa:
    hibernate:
      ddl-auto: update
  secured: true

keycloak:
  auth-server-url: https://keycloak.ric-robotics.xyz
  principal-attribute: idc-system
  realm: ricsg
  resource: ricsg
  public-client: true
  use-resource-role-mappings: false
  bearer-only: true
  cors: true