runtime: java
env: flex
entrypoint: java -Xmx128m -jar demo-0.0.1-SNAPSHOT.jar
service: demo
runtime_config:
    operating_system: "ubuntu22"
    runtime_version: "17"
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 1