server:
  port: 8081
spring:
  cloud:
    gcp:
      sql:
        database-name: ric-database
        instance-connection-name: apt-terrain-401911:asia-southeast1:prd-ric-database
      credentials:
        location: classpath:prod-sql-credential.json
      project-id: apt-terrain-401911
  datasource:
    username: prd-ric-app-user
    password: password
    hikari:
      minimum-idle: 5
  jpa:
    hibernate:
      ddl-auto: update
  secured: true

keycloak:
  auth-server-url: https://keycloak.ric-robotics.xyz
  principal-attribute: info-collection-system
  realm: ricsg
  resource: ricsg
  public-client: true
  use-resource-role-mappings: false
  bearer-only: true
  cors: true