server:
  port: 8080
spring:
  cloud:
    gcp:
      sql:
        enabled: false
  sql:
    init:
      platform: postgres
  datasource:
    url: jdbc:postgresql://10.41.160.3:5432/ric-database
    username: dev-ric-app-user
    password: password
    driverClassName: org.postgresql.Driver
    hikari:
      minimum-idle: 5
  jpa:
    hibernate:
      ddl-auto: update
# For enabling/disabling keycloak integration
  secured: false

keycloak:
  auth-server-url: https://keycloak.ric-robotics.xyz
  principal-attribute: idc-system
  realm: ricsg
  resource: ricsg
  public-client: true
  use-resource-role-mappings: false
  bearer-only: true
  cors: true