server:
  port: 8081
spring:
  cloud:
    gcp:
      sql:
        database-name: ric-database
        instance-connection-name: sapient-symbol-388402:asia-southeast1:dev-ric-database
      credentials:
        location: classpath:sapient-symbol-388402-63f104db32e1.json
      project-id: sapient-symbol-388402
  datasource:
    username: dev-ric-app-user
    password: password
  jpa:
    hibernate:
      ddl-auto: update
  secured: true

keycloak:
  auth-server-url: http://35.247.139.32:8080
  principal-attribute: idc-system
  realm: ricsg
  resource: ricsg
  public-client: true
  use-resource-role-mappings: false
  bearer-only: true
  cors: true