spring:
  cloud:
    gcp:
      sql:
        database-name: ric-database
        instance-connection-name: shaped-splicer-397009:asia-southeast1:prd-ric-database
      credentials:
        location: file:/usr/local/credentials.json
      project-id: shaped-splicer-397009
  datasource:
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    hikari:
      minimum-idle: 5
  jpa:
    hibernate:
      ddl-auto: update
