name: Deploy Frontend to Compute Engine (Production)
on:
  push:
    branches:
      - production/frontend

jobs:
  deploy:
    permissions:
      contents: "read"
      id-token: "write"
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout
        uses: "actions/checkout@v3"

      - name: Build VueJS app
        run: |
          cd ${{ github.workspace }}/Frontend
          npm install
          npm run build
      
      - name: Install SSH key of production server
        uses: shimataro/ssh-key-action@v2.5.1
        with:
          key: ${{ secrets.PRODUCTION_SSH_PRIVATE_KEY }}
          name: id_rsa
          known_hosts: 'unnecessary'

      - name: Adding Known Hosts
        run: |
          ssh-keyscan -H ${{ secrets.PRODUCTION_SSH_HOST }} > ~/.ssh/known_hosts
        
      - name: Fix SSH key
        run: sed -i 's/\r$//g' ~/.ssh/id_rsa

      - name: Upload dist folder to VM instance
        run: |
          rsync -avz -e "ssh" ${{ github.workspace }}/Frontend/dist/ ${{ secrets.PRODUCTION_SSH_USERNAME }}@${{ secrets.PRODUCTION_SSH_HOST }}:/var/containers/apache/docker/volumes/httpd/
